{% set version = "0.61.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinybs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyBS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyBS/shinyBS_{{ version }}.tar.gz
  sha256: 0aed72473060531d0e782ba62092493002137df6b251af9e2294e2a40a32a140

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-shiny >=0.11
  run:
    - r-base
    - r-htmltools
    - r-shiny >=0.11

test:
  commands:
    - $R -e "library('shinyBS')"           # [not win]
    - "\"%R%\" -e \"library('shinyBS')\""  # [win]

about:
  home: https://ebailey78.github.io/shinyBS
  license: GPL-3.0-only
  summary: Adds additional Twitter Bootstrap components to Shiny.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
