travis:
  secure:
    BINSTAR_TOKEN: XPMkXKM0sQ9uB9Xu2Tsb6kxg2DWmQaFHdnzEbUnTA/VFLFK+WpY/c3oMkOVGUOK6neMQ4spFEjIGEx0DfjcBJJCYsPx2g66+PE82iMEhjaNsKCuZC4zC2wGnJY2VF4PnvkEVKS49eK0VsTNZ1a666BusnecAzHPlU5lbnHy3LXXvT2p8H+JtzT2ifq027Jh+io6sCtgOpXJ2UQACLdD2pyAJNtI2SPVmH2vrc8i5huyLgdfBGitcyX8kdJVZhVw5YQ+Zsab6NiayCFkltJgoR8vX6pX3tuQ4RqtO9XqBwFTcVS3qS63n59CohNfNRyGzKSTNRiYq8JNAP2M3yStQIyAxlQPua33H9aQ36vfz41KCVfXr6TXZNpGP2H95tjp4Hqm9UEJc42UIxf5eFFsjkgi8NiGngDI66ziT62npU7VrzcDJC0ujpBcO95A6UW/Ja1nwdlmtiM4vnE50I4srLazi2GgAh6roJtcNA8gqD5EkvDm/YhWw29dg+orzW+nJOkyc0+JPn26xsvO87jJedfH6K1zyeahpuewfA5grTvRGAXjKRHhi80FuOSBFGYPuNsdyQtuqLG4Agrw9vdhwZ4GPkfDm0JrV0INAiOukYISU1Od5+yCAZmM8857EEpieDEC0v2VlFCEmkx8z8C0ZGrTtQnn/5GOrAzYP3T4y2uE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
